export const config = {
  platform: "com.billal.restate",
  endpoint: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  projectId: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID!,
  DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID!,

  AGENT_COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_AGENT_COLLECTION_ID!,

  GALLERIES_COLLECTION_ID:
    process.env.EXPO_PUBLIC_APPWRITE_GALLERIES_COLLECTION_ID!,

  REVIEWS_COLLECTION_ID:
    process.env.EXPO_PUBLIC_APPWRITE_REVIEWS_COLLECTION_ID!,

  PROPERTIES_COLLECTION_ID:
    process.env.EXPO_PUBLIC_APPWRITE_PROPERTIES_COLLECTION_ID!,
};
